import './globals.css'


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
//NODEJS default is server side rendering
//in server side components ,server or machine converts code to html first then sends to browser just the html
//in client side components, browser gets the code and then converts it to html,Code is bundled into JavaScript and sent to the browser.Great for interactive UI, like buttons, forms, animations, etc.